/*-----------------------------------------------------------------
Header file: error.h

Header file van de file error.c.

auteur : W.L. Li
datum  : januari 1998
-------------------------------------------------------------------*/


extern void print_syntax_error(char error, char *string);
extern void print_run_time_error(char error, char *string);
extern void print_error(char error, char *string);
